#!/bin/bash

REPO="whoami"
TOKEN="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"
USER="Amyn00"


git status

git add .

read -p "write you message here: " msg
git commit -m "$msg"

if git ls-remote -l "$REPO" -q -t "$TOKEN" &> /dev/null
then
	git pull

	git push
else
	echo "generate new token!"
	read -p "write your new Token: " nTOKEN
	git remote set-url origin https://$USER:$nTOKEN@github.com/$USER/$REPO.git
	export TOKEN="$nTOKEN"
	git pull
	git push
fi
